### ISSUE TITLE
Point libraries documentation links to the latest stable version.

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/pyansys#171]
🐞 **Problem**
Some links are pointing to invalid directions due to the old multi-version logic. See #170. These links need to point to the stable documentation as soon as the new multi-version logic gets released and adopted by projects.

**Comment by RobPasMue** [comment]
WIP:
- [ ] Checking links to multiversion docs
- [ ] Enable multiversion for the ``pyansys`` metapackage

**Comment by RobPasMue** [comment]
This has been solved in #275 - finally closing!
