### ISSUE TITLE
Change PyDPF-Core and PyDPF-Post thumbnail images

### ISSUE THREAD

**Issue by PProfizi** [ansys/pyansys#213]
### Description of the modifications

Create better illustrations for the ansys-dpf-core and ansys-dpf-post thumbnail images on the PyAnsys documentation landing page.

Change the pydpf-core picture [here](https://github.com/pyansys/pyansys/blob/main/doc/source/_static/thumbnails/pydpf-core.png).
Add a pydpf-post picture and link it [here](https://github.com/pyansys/pyansys/blob/main/doc/source/index.rst).

**Comment by RobPasMue** [comment]
Thanks for handling this @PProfizi ! Format should be 640x480

**Comment by RobPasMue** [comment]
Closed by #259
