### ISSUE TITLE
Embed meilisearch indices for all public docs in PyAnsys main documentation

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyansys#298]
Pinging @Revathyvenugopal162 @jorgepiloto 

We should implement the search on all public facing indices inside the main PyAnsys docs. Could you two take care of this?

**Comment by RobPasMue** [comment]
@Revathyvenugopal162 - could you get on this?

**Comment by Revathyvenugopal162** [comment]
Sure, it will be easy through ansys/action@4., so i can implement this after the action gets released ( planned for today).

**Comment by RobPasMue** [comment]
I'm guessing you are referring to ``4.1``...

**Comment by Revathyvenugopal162** [comment]
thnaks @RobPasMue yes, it is 4.1

**Comment by RobPasMue** [comment]
Yep, no big deal. We'll wait =)

**Comment by RobPasMue** [comment]
Hi @Revathyvenugopal162! Could you get back to this whenever you have the chance? =)

**Comment by Revathyvenugopal162** [comment]
@RobPasMue Sure. on it.

**Comment by RobPasMue** [comment]
Closed by #334
