### ISSUE TITLE
Search in edge is giving wrong website

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/pyansys#450]
From edge if we are searching for pyansys , sometimes it is showing the old page 
![image](https://github.com/ansys/pyansys/assets/104772255/a1a1bcbe-868f-42f1-bbca-9f9b7692c634)
 liking to the old repo because of the https://github.com/ansys/pyansys/tree/gh-pages/dev folder.  Remove the dev folder.

**Comment by RobPasMue** [comment]
``dev`` directory deleted. Should be solved now. Let's give some time to the crawlers
