### ISSUE TITLE
Migrate to Ruff

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/pyansys#746]
Right now, the project uses [Black], [Isort], and [Flake8] for as linters. We can migrate to [Ruff] since it collects all of them in a single tool.

[Black]: https://github.com/psf/black
[Isort]: https://pycqa.github.io/isort/
[Flake8]: https://flake8.pycqa.org/en/latest/
[Ruff]: https://docs.astral.sh/ruff/

**Comment by moe-ad** [comment]
Hi @jorgepiloto @RobPasMue.

Initial investigation already shows that we have **black**, **isort**, and **flake8** configured for pre-commit checks, so .pre-commit-config.yaml needs to be updated for the migration to **ruff**.

However, I am also curious to know if any of the current linters are individually configured for running checks in some of the ansys actions being used in the workflows for this repo, so I can update these actions. Is this the case?

**Comment by RobPasMue** [comment]
Each repository defines its tools. Our ansys/actions only perform calls to pre-commit. We do not configure flake8, black or any other tool for them. That is the responsibility of each repository. We can provide recommendations though.
