### ISSUE TITLE
Reduce the addition and maintenance of new projects

### ISSUE THREAD

**Issue by moe-ad** [ansys/pyansys#755]
A number of files (**e.g.** [**pyproject.toml**](https://github.com/ansys/pyansys/blob/main/pyproject.toml), [**links.py**](https://github.com/ansys/pyansys/blob/main/tools/links.py), [**examples.rst**](https://github.com/ansys/pyansys/blob/main/doc/source/examples.rst) to name a few) have to be edited manually each time there is a new addition/subtraction to/from the pyansys metapackage. This issue will address removing this manual process by:

1. Adding a new file (a .yml for example) which will be the only data source that will need maintenance.
2. Creating a setup.py that will update every other file automatically as needed.

**Comment by greschd** [comment]
Something closer to the original suggestion which I'd also consider workable is:
- a source `.yml`
- template files for `links.py`, `examples.rst` etc, for example in Jinja2 format
- a pre-commit hook which interpolates the templates and produces the actual files
- for `pyproject.toml` the update would be a bit more complicated, as we'd want to keep it as source of truth for the versions (to allow dependabot to work)

**Comment by RobPasMue** [comment]
Works too =)

**Comment by moe-ad** [comment]
Thank you both for your valuable inputs @greschd and @RobPasMue. We will start exploring doing this in a way similar to your suggestions. Once the final solution becomes available, I will tag you both for additional inputs.

**Comment by jorgepiloto** [comment]
Let's start by creating the YML file:

```yaml
projects:

  pymapdl:
    name: ...    
    repository: ...
    thumbnail: ...

  ...

```
